FROM alpine:latest

RUN apk update
RUN apk add build-base clang lld llvm mtools nasm bc cpio gettext perl xorriso meson ninja git bison cmake rsync gzip flex diffutils findutils wget ca-certificates ssl_client linux-headers pkgconf pkgconf-dev libffi-dev expat-dev libxml2-dev xkeyboard-config elfutils-dev openssl-dev ncurses-dev

