FROM alpine:latest

RUN apk update
RUN apk add build-base clang lld llvm mtools nasm bc cpio gettext perl xorriso meson ninja git bison cmake rsync gzip flex coreutils diffutils findutils wget ca-certificates ssl_client linux-headers linux-pam-dev pkgconf-dev libffi-dev expat-dev libxml2-dev wayland-dev wayland-protocols xkeyboard-config elfutils-dev openssl-dev ncurses-dev gmp-dev mpfr-dev mpc1-dev isl-dev

