#!/bin/sh

mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

for s in /etc/init.d/S*; do
    if [ -x "$s" ]; then
        "$s" start
    fi
done

echo -e "Welcome to \033[1;34mEaMS Linux\033[0m!"
